name: platform_design
description: A project showcasing a Flutter app following different platform IA conventions.
version: 1.0.0+1

environment:
  sdk: ^3.2.0

dependencies:
  english_words: ^4.0.0
  flutter_lorem: ^2.0.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_chat_ui: ^1.6.10
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  path: ^1.8.3
  firebase_core: ^2.25.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
