name: platform_design
description: A project showcasing a Flutter app following different platform IA conventions.
version: 1.0.0+1

environment:
  sdk: ^3.2.0

dependencies:
  english_words: ^4.0.0
  flutter_lorem: ^2.0.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_chat_ui: ^1.6.10
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  path: ^1.8.3
  firebase_core: ^2.25.3
  cloud_firestore: ^4.14.0
  http: ^1.2.0
  bubble: ^1.2.1
  firebase_auth: ^4.17.3
  email_validator: ^2.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Blacknorthdemo
      fonts:
        - asset: fonts/Blacknorthdemo-mLE25.otf
    - family: Moonchild
      fonts:
        - asset: fonts/Moonchild.ttf