name: platform_design
description: A project showcasing a Flutter app following different platform IA conventions.
version: 1.0.0+1

environment:
  sdk: ^3.2.0

dependencies:
  english_words: ^4.0.0
  flutter_lorem: ^2.0.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_chat_ui: ^1.6.10
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  path: ^1.8.3
  firebase_core: ^2.25.3
  cloud_firestore: ^4.14.0
  http: ^1.2.0
  bubble: ^1.2.1
  firebase_auth: ^4.17.3
  email_validator: ^2.1.17
  shared_preferences: ^2.2.2
  permission_handler: ^11.2.0
  cached_network_image: ^3.3.1
  firebase_storage: ^11.6.4
  image_picker: ^1.0.7
  flutter_svg: ^2.0.9
  google_sign_in: ^6.2.1
  loading_animation_widget: ^1.2.0+4
  double_back_to_close_app: ^2.1.0
  aura_box: ^1.0.2
  is_first_run: ^1.0.0
  flutter_carousel_widget: ^2.2.0
  flutter_animate: ^4.5.0
  page_transition: ^2.1.0
  fluttertoast: ^8.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Blacknorthdemo
      fonts:
        - asset: fonts/Blacknorthdemo-mLE25.otf
    - family: Moonchild
      fonts:
        - asset: fonts/Moonchild.ttf

